name: 'Verify Commit Signatures'
description: 'Fails if a commit isn’t signed with a non-exportable key'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  USERS_DIR:
    description: 'Public keys and attestation certs for authorized committers'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'user-check'
  color: 'blue'
