name: Verify commits
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  verify-commits:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Import certificates
      run: |
        for dir in $(ls .GITHUB_SIGNATURE_VERIFICATION); do
          echo "Importing public keys from directory $dir"
          for file in $(ls .GITHUB_SIGNATURE_VERIFICATION/$dir); do
            echo "Extracting public key from signer certificate"
            echo openssl x509 -pubkey -noout -in .GITHUB_SIGNATURE_VERIFICATION/$dir/signer.pem
            openssl x509 -in .GITHUB_SIGNATURE_VERIFICATION/$dir/signer.pem -inform PEM -out public_key.gpg -outform DER
            echo "Importing public_key.gpg"
            gpg --import public_key.gpg
          done
        done

    - name: "Verify commits"
      uses: avri-schneider/verify-commit-signature-action@main
      with:
        USERS_DIR: '.GITHUB_SIGNATURE_VERIFICATION'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
