name: Verify commits
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  verify-commits:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Import certificates
      run: |
        echo import Github public GPG key
        gpg --batch --gen-key <<EOF
        %echo Generating a key with password protection
        Key-Type: RSA
        Key-Length: 4096
        Subkey-Type: RSA
        Subkey-Length: 4096
        Name-Real: Your Name
        Name-Comment: GitHub Actions
        Name-Email: you@example.com
        Expire-Date: 0
        Passphrase: your_secret_password
        %commit
        EOF
        gpg --keyserver hkp://keys.gnupg.net --recv-keys 4AEE18F83AFDEB23
        gpg --lsign-key 4AEE18F83AFDEB23

        for dir in $(ls .GITHUB_SIGNATURE_VERIFICATION); do
          echo "Importing public keys of $dir"
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/users/avri-schneider/gpg_keys | jq -r '.[].raw_key' | gpg --import
        done
#          for file in $(ls .GITHUB_SIGNATURE_VERIFICATION/$dir); do
#            echo "Extracting public key from signer certificate"
#            echo openssl x509 -pubkey -noout -in .GITHUB_SIGNATURE_VERIFICATION/$dir/signer.pem
#            openssl x509 -in .GITHUB_SIGNATURE_VERIFICATION/$dir/signer.pem -inform PEM -out public_key.gpg -outform DER
#            echo "Importing public_key.gpg"
#            gpg --import public_key.gpg
#          done
#        done

    - name: "Verify commits"
      uses: avri-schneider/verify-commit-signature-action@main
      with:
        USERS_DIR: '.GITHUB_SIGNATURE_VERIFICATION'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
